apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: test-user
spec:
  request: <<replace your csr>>
  signerName: kubernetes.io/kube-apiserver-client
  usages:
    - client auth
